### ISSUE TITLE
向大佬请教一个hexo博客配置问题！

### ISSUE THREAD

**Issue by glennwu97** [TransparentLC/transparentlc.github.io#1]
大佬你好,想向你请教下你博客封面里的本页浏览量和总页浏览量是怎么实现的呢? 今天在material主题目录下的sidebar_navigation.ejs里新建了一个类折腾了很久都没有实现,十分好奇。
![](https://gitee.com//gleenwu/picbed01/raw/master/img/20200314125738.jpg)

**Comment by glennwu97** [comment]
大佬你好，这个问题我已解决就不麻烦啦，不过有两个新的问题就是请问如何实现博客文章图片放大和代码拷贝功能呢?

**Comment by TransparentLC** [comment]
总感觉好像有人问过类似的东西了……在[这里](https://akarin.dev/2020/02/07/alicdn-video-hosting/)的评论区有解释 (=ﾟωﾟ)=

*看了一下 ID 原来是同一个人，那先 close 了 2333*

**Comment by glennwu97** [comment]
哈哈哈 好的。




| |
glennw97
|
|
邮箱：glennw97@163.com
|

Signature is customized by Netease Mail Master

在2020年07月10日 20:11，✨小透明・宸✨ 写道：

总感觉好像有人问过类似的东西了……在这里的评论区有解释 (=ﾟωﾟ)=

看了一下 ID 原来是同一个人，那先 close 了 2333
