### ISSUE TITLE
URL cannot reach

### ISSUE THREAD

**Issue by KevinZonda** [TransparentLC/transparentlc.github.io#2]
In article <https://akarin.dev/2019/06/05/powershell-multithread-download/>, the source code download link canno be reached easily. The file is very useful to me. Please provide another way to download it! QwQ
Thanks a lot! Have a good day! :) ❤

**Comment by TransparentLC** [comment]
The link is broken... But I have uploaded the code to [GitHub Gist](https://gist.github.com/TransparentLC/7a37a7867b0f65c0068035d00f49e09b) (=ﾟωﾟ)=

**Comment by KevinZonda** [comment]
SGTM. You should also update Markdown file! Have good night! (*^_^*)
